### ISSUE TITLE
CloudWatchAppender: Does not handle Log event too large

### ISSUE THREAD

**Issue by ljett** [kdgregory/log4j-aws-appenders#121]
AWS has a limit of 256kb (262144) on a single LogEvent.

While it is not explicitly called out in their API documentation, you can see it on the cloudwatch logs quotas page under "Event size":
https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/cloudwatch_limits_cwl.html

The appender does not check for this and continues to retry on these exceptions.

```
ERROR failed to send batch com.amazonaws.services.logs.model.InvalidParameterException: Log event too large: 672494 bytes exceeds limit of 262144 (Service: AWSLogs; Status Code: 400; Error Code: InvalidParameterException; Request ID: b8c9178a-fb3b-4720-81fb-799558ce19f8)
```

The appender should either drop these messages, truncate them, or split them into multiple messages.

**Comment by kdgregory** [comment]
@ljett - thanks for pointing this out. Too-large messages should be rejected by the appender and never get to this point. I have two questions:

1. Which logging framework are you using (Log4J 1.x, Log4J 2.x, or Logback)?
2. Do your messages contain characters from outside the USASCII character set?

My thought is that the initial check passes because it's based on string length, but the actual send fails after UTF-8 conversion.

I will look into it in more detail this week.

**Comment by kdgregory** [comment]
I'll be changing the test, and also adding a configuration parameter that will allow user control over whether long messages are dropped or truncated.

I've also submitted feedback to the AWS documentation team.

**Comment by ljett** [comment]
I am using Log4j 2.x - and I utilized the pattern layout truncation in order to work around this in the meantime: https://logging.apache.org/log4j/log4j-2.8/manual/layouts.html#PatternLayout

But yes, the api documentation talks about the maximum batch size which is what the code is checking for. 

The 256kb log event limit is documented, but as a service quota, not as a limit on the API Reference.

https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/cloudwatch_limits_cwl.html

```
Event size | 256 KB (maximum). This quota can't be changed.
```

**Comment by kdgregory** [comment]
Added a configuration parameter, `truncateOversizeMessages`, to all appenders. If `true` (the default), the message is truncated; if `false` it is discarded. In either case the event is logged using the framework's internal debug logger, and the number of oversize messages is available as a JMX parameter.

While in the code, I also configured it to discard zero-length messages. These shouldn't happen unless the layout is misconfigured, but while in the code ...

I went back and forth on whether truncation should be the default, because it will corrupt JSON log messages. However, I think that the primary reason for an oversize message is some form of exception reporting (eg, Spring), and it's important to see those.

@ljett - this should be available on Maven Central later today, as version 2.4.1.
