### ISSUE TITLE
Add property "ignoreExceptions" to CloudWatchAppender similar to RollingFile appender in core log4j2

### ISSUE THREAD

**Issue by landrus** [kdgregory/log4j-aws-appenders#140]
I would like to use the CloudWatchAppender in a failover configuration. For this to work correctly, exceptions raised by the CloudWatchAppender have to be passed through, so the FailOver appender can pick these up and forward the log request to the list of failover appenders.

See [log4j2 Failover appender](https://logging.apache.org/log4j/2.x/manual/appenders.html#FailoverAppender).

**Comment by kdgregory** [comment]
@landrus - I'm sorry, but this feature does not fit with the architecture of this library.

With `RollingFileAppender` (or many other appenders), each `append()` translates directly to some action that will fail in a clear and non-recoverable way (eg, user exceeds quota or maximum file size).

With my library, there are two things that get in the way. The first is that the appender does not perform the write itself: it adds a message to a queue, and the log-writer sends a batch of messages to AWS. This behavior happens even in "synchronous mode"; the only difference is that the writer immediately builds and sends the batch. It would be _possible_ to propagate exceptions in this case, but that brings up the second issue.

AWS has many "retryable" error conditions. For example, any AWS request can be throttled due to concurrent load. My appenders catch this, and attempt to retry the request several times (with exponential backoff). If unable to do so, they silently return the messages to the queue and try again later.

Should this situation cause the appender to give up right away and throw an exception? If your reason for using `FailoverAppender` is to guarantee that you won't lose messages, the answer is yes. However, throttling is an expected part of AWS operation: shutting down an appender just because it got throttled once is not, in my opinion, a viable action.

If your goal _is_ to ensure that you don't suffer message loss, then I think a better solution is redundancy, not failover: write to CloudWatch _and_ a file appender that has `bufferedIO` false and `immediateFlush` true (and recognize that doing this inline will signficantly impact the performance of your application).
