### ISSUE TITLE
Queue is getting full, how can i increase the size?

### ISSUE THREAD

**Issue by MukulitBhati** [kdgregory/log4j-aws-appenders#148]
we are getting a lot of logs as it's an application with thousands of threads running, we are getting almost 800 to 900 kb logs per second.
I have already configured this library with log4j1 and it's working fine, I am getting my logs on cloud watch.

so, The writer thread is a single thread that is writing logs from the queue to cloud watch or it's a multiple threads writer?
I am asking it as I observed our heap utilisation is increasing surprisingly. could anyone please help me to understand how the writer is writing logs from queue to cloudwatch?

**Comment by kdgregory** [comment]
@MukulitBhati - To answer your immediate question, there is only a single writer thread per appender. Multiple threads would probably decrease performance, as they would need to coordinate use of a single sequence token per log stream.

Some ideas to improve performance (in order of impact to your application):

* Change the `batchDelay` parameter to 250. The default is 2000, which could easily cause a backup if you're writing a large number of logs. You can't go below 250 because CloudWatch imposes an unchangeable quota of 5 requests per second (so yes, technically you could go to 200, but the likelihood of exceeding quota in any given second would make that a bad idea).

* Create multiple appenders in your logging config, _writing to different streams,_ For example, split your application into "front end" and "back end" components, which log to a different appender. This should allow you to scale your throughput linearly, at the cost of putting related messages in different streams.

* Switch your logging framework to Kinesis. This is a major infrastructure change, and would require adding some destination (such as Elasticsearch). However, you can scale Kinesis simply by adding more shards to the stream.

As for the heap utilization, I can't speak to that. The implementation uses a `LinkedBlockingDeque` for communication between the appender and logwriter, so the utilization should be relatively constant if input rate matches output, and not dependent on the number of threads writing (unlike a copy-on-write list). However, if are writing more than reading, it could easily get backed up, especially if you've increased `discardThreshold`.
