### ISSUE TITLE
Spark on EC2 server - creating log group and log stream but no logs

### ISSUE THREAD

**Issue by monikadr** [kdgregory/log4j-aws-appenders#185]
Hello, 
I tried to use this in my spark application that is running on EC2 Cluster nodes. It is creating log group and log streams, but actual logs are not streamed to cloudwatch. Any help?

**Comment by kdgregory** [comment]
If the appender is being initialized, _and the logging framework does not re-initialize with different appenders_ then the most likely cause is that you haven't granted your instance permission to invoke `PutEvents`. Required permissions are listed [here](https://github.com/kdgregory/log4j-aws-appenders/blob/trunk/docs/permissions.md).

There's also a troubleshooting guide that should help: https://github.com/kdgregory/log4j-aws-appenders/blob/trunk/docs/troubleshooting.md

You may need to enable batch-level logging (described in that guide).

**Comment by monikadr** [comment]
I tried running with debug, and I dont see any errors. I see a message saying "log writer initialization complete" (attached screenshot ). For the permission access, I have given full log access - but still logs are not coming
"Action": [
                "logs:*"
            ],

![image](https://github.com/kdgregory/log4j-aws-appenders/assets/26071599/9f92fedb-6611-44d6-8494-8f3c7f7932b0)

**Comment by kdgregory** [comment]
If you've enabled batch logging as shown in the troubleshooting guide, and aren't seeing messages that the batches are being written, then there are a few possible causes:

* The appender isn't getting any messages. This could happen because the logger level is set too high, or it's configured for the wrong name (eg, "com.myprject" rather than "com.myproject"), or the application just isn't writing any logs.
* The logging framework is being reconfigured. To test this, replace the CloudWatch appender with a file appender, and verify that the file is being written.
* The program is being shut down before the appender has a chance to write its batch. This shouldn't happen, as there's a shutdown hook that forces a last write before allowing the program to shut down. It's possible that Spark is disabling this. One way to check is to see if the program runs longer than your configured batch interval (by default, 2 seconds).

Other than that, I can't provide much more help. I haven't used my library with Spark, so don't know any quirks of how it interacts with a logging library.

**Comment by kdgregory** [comment]
I'm going to assume that you were able to resolve this.
