### ISSUE TITLE
High Heap Memory 

### ISSUE THREAD

**Issue by RajeshCoast** [kdgregory/log4j-aws-appenders#194]
Dear Sir,

We are getting the high heap memory. We have discardThreshold(250) and batchDelay(500). 

But still getting high heap. Can you please help us in setting the attributes which can reduce heap memory.

Regards

**Comment by kdgregory** [comment]
@RajeshCoast - as I said when you last asked this question, it is extremely unlikely to be caused by this appender library. I have neither the time nor the inclination to help you debug your application. Especially since you have given absolutely no information about why you think that this library is the cause of your problem.
