### ISSUE TITLE
FeatureRequest | Publish keyvalue pairs in JsonLayout

### ISSUE THREAD

**Issue by anoopnarang** [kdgregory/log4j-aws-appenders#202]
I found this library extremely good at what it does. The docs are on the point and its user friendly. 

I had a requirement where I wanted to push json logs to cloudwatch for a specific stream in my application. In some of the logs, I wanted to add some specific attributes without messing up other loggers. Now, I know I can set it in MDC and remove them just after the use of log statement. But I noticed for this specific purpose concept of [keyvalue pairs](
https://www.slf4j.org/api/org/slf4j/event/LoggingEvent.html#getKeyValuePairs()) has been added to ILoggingEvent. 

So my log statement would look something like below:  _(Its basically using the new [LoggingEventBuilder](https://www.slf4j.org/apidocs/org/slf4j/spi/LoggingEventBuilder.html) )_
```
        logger.atInfo()
                .addKeyValue("key1", "value1")
                .addKeyValue("key2", "value2")
                .log("This is a test log message");
 ```
 
 I notice that same could be accessed in [JsonLayout](https://github.com/kdgregory/log4j-aws-appenders/blob/trunk/library/logback-appenders/src/main/java/com/kdgregory/logback/aws/JsonLayout.java) and published along with MDC.
 
 I am happy to raise a PR but got scared away by [NoContributions](https://github.com/kdgregory/log4j-aws-appenders?tab=readme-ov-file#contributions).

**Comment by kdgregory** [comment]
@anoopnarang 

Thanks for the well-documented request. It seems like a reasonable addition.

My one concern is that `ILoggingEvent.getKeyValuePairs()` was added in 1.3, so support for it would break backwards compatibility for people using 1.2.x.

However, I'm pretty sure that I can make it work using an opt-in helper class. So to enable you'd configure with `includeKeyValuePairs=true`. I think the key-value pairs should be in their own sub-object, which I'm thinking can be named `eventData` or `additionalData`.

I think it will be a few weeks before I can get to this, and I do want to hold to the no-contributions policy. The delay is primarily due to testing; if you really want it sooner, you could fork and do an always-on implementation (I realize that only works if you are a single-person shop or have an artifact repo where you can store the fork).

**Comment by kdgregory** [comment]
Looking into this, and 1.3 also made a breaking change to the `AccessEvent` constructor.

I'm going to do a first pass using reflection, then see whether it's even worthwhile to use actual classes. I think reflection may be sufficiently performant.

**Comment by anoopnarang** [comment]
@kdgregory 
I went with some other route to solve my problem _( using this library )_. So, this feature is not needed by me anymore, Please close the request if needed.

**Comment by kdgregory** [comment]
Thanks for letting me know, but I do think it's a good enhancement. If you're interested, the first pass, using reflection, is in branch `dev-3.2.1`, but is missing tests and documentation. That may be the final implementation, since there were other backwards-incompatible changes in Logback 1.3.0.

**Comment by kdgregory** [comment]
Ran a [benchmark](https://github.com/kdgregory/log4j-aws-appenders/files/15141882/KeyValueExtractionBenchmark.txt) to compare reflection with direct access via the new classes. 

Direct access was 996 ms for 10MM reps, while reflection took 1153 ms.

I don't see any reason to replace the reflection-based implementation, so will clean that up a bit and release (probably next weekend).

*Update:* I also tried a benchmark with method handles, which took around 1200 ms per run. So sticking with reflection.

**Comment by kdgregory** [comment]
Everything's done, but integration tests are failing due to what appears to be an AWS bug: sending a batch of records immediately after creating the stream fails with `ResourceNotFoundException`.  Subsequent batches send without a problem, and all of the assertions pass except for the one that looks for an empty error log.

I've replicated this behavior with a test program, and will send to AWS. Even if they agree that it is a bug, versus "expected behavior", it may take a long time to resolve. I don't want to remove the log checks from the integration tests, but I might do so for this release.
