### ISSUE TITLE
Log4j Cloudwatch logging does not work with war file deployment to Amazon ElasticBeans

### ISSUE THREAD

**Issue by MohdRash** [kdgregory/log4j-aws-appenders#34]
I am using a custom log4j AWS log appender (https://github.com/kdgregory/log4j-aws-appenders) to write my application logs to Amazon cloud watch.

When I run the application from my box, I can see logs have been successfully sent to Amazon cloud watch.

However, when I deploy the application to Amazon ElasticBeans, it does not work.

Any help?

**Comment by kdgregory** [comment]
@MohdRash - I've been running in an Elastic Beanstalk deployment with no problems. If you're able to run it locally, then I suspect that the issue is a permissions problem on the Elastic Beanstalk instance.

The AWS appenders will write any error messages to the Log4J internal logger. I _believe_ this is enabled by default on an ElasticBeanstalk, but if not you can add `-Dlog4j.debug=true` to your Java runtime options.

Next, you'll need to log into the EC2 instance, and look at the local logfiles. Assuming that you're using Tomcat 8, they'll be in `/var/log/tomcat8`. You want to look at the `catalina.out` logfile from server startup (note that EB rotates logfiles), and look for `LogLog` lines. Shortly after server startup you should see the appender configuration, along with any errors that the appender received.

If the appender is unable to connect to CloudWatch, it will stop trying, and also discard any messages (to prevent out-of-memory errors).

**Comment by kdgregory** [comment]
Alternatively, you could check the [instance profile](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/concepts-roles-instance.html) that's used by your beanstalk environments. It must contain the permissions specified [here](https://github.com/kdgregory/log4j-aws-appenders/blob/master/docs/cloudwatch.md#permissions).

**Comment by kdgregory** [comment]
Closing this issue. Have responded here and on [Stack Overflow](https://stackoverflow.com/q/49121643/42126), so I'm assuming that either the OP's issue is solved or he is no longer using the library.
