### ISSUE TITLE
Configuration with EMR

### ISSUE THREAD

**Issue by austince** [kdgregory/log4j-aws-appenders#55]
Hi, thanks for the great package!

I'm wondering if you have any experience running this on AWS EMR, which I believe uses Logback, or a cluster where logging is provided. I don't have a lot of experience with log4j (or slf4j) and am wondering if you know of any special configuration that needs to be done.

**Comment by kdgregory** [comment]
@austince - unfortunately, I don't think I'll be much help. I have fought with EMR and logging several times, and every time I've lost. Most recently when putting together a talk on centralized logging, in which I tried both EMR and a stand-alone Hadoop install (I ended up using Spark for my example).

The problem is that Hadoop includes its own logging configuration file. I _think_ you should be able to replace this configuration file in one of the bootstrap steps, but as I said, I've been unsuccessful.

You could also explicitly re-initialize the logging framework from within your job, using a differently-named configuration file. You can see an example of doing this in the unit and integration tests. The problem with doing this on EMR is that some logging will go to your destination, and some (cluster startup and management will still go to the default location.

As for Log4J versus Logback: I'm pretty sure that Hadoop uses Log4J, but newer versions might have switched. If that's the case, be aware that Logback support from this library won't be available until some time in December.

**Comment by austince** [comment]
Hi @kdgregory, thank you so much for the thorough reply. Good to know I'm not the only one in a losing battle with EMR logs. I'll see if I can make headway replacing the logging file, thanks again!
