### ISSUE TITLE
Failed to stop/remove thread and Threadlocal.

### ISSUE THREAD

**Issue by gsrikanth007** [kdgregory/log4j-aws-appenders#56]
Thank you for the appender! I am getting below exception when i am stopping my tomcat server where my app is deployed.

WARNING: The web application [APPNAME] appears to have started a thread named [com-kdgregory-aws-logwriter-log4j-cloudwatch-0] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(Unknown Source)
 java.util.concurrent.LinkedBlockingDeque.pollFirst(Unknown Source)
 java.util.concurrent.LinkedBlockingDeque.poll(Unknown Source)
 com.kdgregory.logging.common.util.MessageQueue.dequeue(MessageQueue.java:174)
 com.kdgregory.logging.aws.internal.AbstractLogWriter.buildBatch(AbstractLogWriter.java:308)
 com.kdgregory.logging.aws.internal.AbstractLogWriter.run(AbstractLogWriter.java:176)
 java.lang.Thread.run(Unknown Source)
Nov 14, 2018 12:57:35 PM org.apache.catalina.loader.WebappClassLoaderBase checkThreadLocalMapForLeaks
**SEVERE:** The web application [APPNAME] created a ThreadLocal with key of type [com.kdgregory.log4j.aws.JsonLayout$1] (value [com.kdgregory.log4j.aws.JsonLayout$1@7ed06e33]) and a value of type [com.kdgregory.logging.common.util.JsonConverter] (value [com.kdgregory.logging.common.util.JsonConverter@28fcb58a]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.

**Comment by kdgregory** [comment]
@gsrikanth007 - is this happening when you actually stop the Tomcat server from running, or when you undeploy or redeploy your application?

If the former, it's a spurious exception: the app-server is no longer running, so neither are the threads in it.

However, I suspect it's the latter, and if so it is a real issue, although I'm not sure that it's one that I'll be able to solve within the library.

What's happening is that the web-app is unloaded, but Log4J is not being told to shut down. In the normal case, this isn't an issue: eventually the web-app classloader gets collected, along with all of the resources used by the web-app. However, the writer thread relies on an explicit Log4J shutdown, so it will keep running after the web-app is unloaded. And since it has a reference to the writer object, it will prevent the classloader from being collected.

The work-around -- maybe the only solution -- is to implement a `ServletContextListener` and explicitly shut down Log4J in its `contextDestroyed()` method by calling `LogManager.shutdown()`.

I may also be able to implement something within the library using weak references. While I think about that I'll leave this issue open.

**Comment by kdgregory** [comment]
To set expectations: right now I'm focused on adding Logback support. I expect this to be wrapped up in early December, then will look into possible thread-management solutions.

**Comment by kdgregory** [comment]
@gsrikanth007 - I've been looking at this, and it appears that the standard approach is to use a context listener. In fact, both Logback and Log4J2 provide one as part of their standard distribution. I will be writing up a FAQ entry on this, with example code, but as I mentioned above it will take a back seat to the Logback integration.

**Comment by gsrikanth007** [comment]
Thanks for the reply, @kdgregory 
`Logmanager.shutdown()` will stop the WARNING but the **SEVERE** issue about JSON Layout is still appearing

Also, I had some exception about IdleConnectionReaper and I had to shutdown that as well using `com.amazonaws.http.IdleConnectionReaper.shutdown();`

`SEVERE: The web application [Web2LeadService] created a ThreadLocal with key of type [com.kdgregory.log4j.aws.JsonLayout$1] (value [com.kdgregory.log4j.aws.JsonLayout$1@7ed06e33]) and a value of type [com.kdgregory.logging.common.util.JsonConverter] (value [com.kdgregory.logging.common.util.JsonConverter@28fcb58a]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.`

**Comment by kdgregory** [comment]
I've been digging into this, and am seeing that the writer thread does not get interrupted when the appender is stopped. It's unclear why this is happening, but is definitely a bug.

**Comment by kdgregory** [comment]
@gsrikanth007 - version 2.0.1 is now available on Maven Central. It fixes the bug (long wait at shutdown) and also includes [an example web-app](https://github.com/kdgregory/log4j-aws-appenders/tree/master/examples/log4j1-webapp) and [a documentation update](https://github.com/kdgregory/log4j-aws-appenders/blob/master/docs/tomcat.md).
