### ISSUE TITLE
Enable users to be able to run the examples locally

### ISSUE THREAD

**Issue by rohitaila** [kdgregory/log4j-aws-appenders#85]
I wanted to know if there is a way to run these examples in a local environment that invokes my default AWS account that has been configured there.

**Comment by kdgregory** [comment]
@rohitaila - yes, in fact that's how I run them. What happens when you try?

**Comment by kdgregory** [comment]
The logging framework will use the client factories if available in your SDK version (they are in the version used by the examples). These factories use the [DefaultAWSCredentialsProviderChain](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/DefaultAWSCredentialsProviderChain.html), which will attempt to retrieve credentials from a variety of sources (see link). If you need greater control over the credentials (such as a non-standard profile), you can implement a static method to create the client.

This is all documented [here](https://github.com/kdgregory/log4j-aws-appenders/blob/master/docs/service-client.md).

I personally prefer using environment variables, which are loaded at the time I log in. This is because I typically work with a single "developer" account and then assume a role to access different accounts in the organization.
